default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  pool: 50
  timeout: 5000

development:
  <<: *default
  database: society_reviews_development 

test:
  <<: *default
  database: society_reviews_test
